config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  resource :first_run, only: %i[ show create ]

  resource :session, only: %i[ new create destroy ] do
    scope module: "sessions" do
      resources :transfers, only: %i[ show update ]
    end
  end

  get "join/:join_code", to: "users#new", as: :join
  post "join/:join_code", to: "users#create"

  resource :account do
    scope module: "accounts" do
      resource :join_code, only: :create
      resource :custom_styles, only: %i[ edit update ]
    end
  end

  resources :books, except: %i[ ] do
    resource :publication, controller: "books/publications", only: %i[ show edit update ]
    resource :bookmark, controller: "books/bookmarks", only: :show

    scope module: "books" do
      namespace :leaves do
        resources :moves, only: :create
      end

      resource :search
    end

    resources :sections
    resources :pictures
    resources :pages
  end

  get "/:id/:slug", to: "books#show", constraints: { id: /\d+/ }, as: :slugged_book
  get "/:book_id/:book_slug/:id/:slug", to: "leafables#show", constraints: { book_id: /\d+/, id: /\d+/ }, as: :slugged_leafable

  direct :book_slug do |book, options|
    route_for :slugged_book, book, book.slug, options
  end

  direct :leafable_slug do |leaf, options|
    route_for :slugged_leafable, leaf.book, leaf.book.slug, leaf, leaf.slug, options
  end

  resources :pages, only: [] do
    scope module: "pages" do
      resources :edits, only: :show
    end
  end

  resources :qr_code, only: :show
  resources :users do
    scope module: "users" do
      resource :profile
    end
  end

  direct :leafable do |leaf, options|
    route_for "book_#{leaf.leafable_name}", leaf.book, leaf, options
  end

  direct :edit_leafable do |leaf, options|
    route_for "edit_book_#{leaf.leafable_name}", leaf.book, leaf, options
  end

  namespace :action_text, path: nil do
    get "/u/*slug" => "markdown/uploads#show", as: :markdown_upload
    post "/uploads" => "markdown/uploads#create", as: :markdown_uploads
  end

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/user.rb
class User < ApplicationRecord
  include Role, Transferable

  has_many :sessions, dependent: :destroy
  has_secure_password validations: false

  has_many :accesses, dependent: :destroy
  has_many :books, through: :accesses
  has_many :leaves, through: :books

  after_create :grant_access_to_everyone_books

  scope :active, -> { where(active: true) }
  scope :ordered, -> { order(:name) }

  def current?
    self == Current.user
  end

  def deactivate
    transaction do
      sessions.delete_all
      update! active: false, email_address: deactived_email_address
    end
  end

  private
    def deactived_email_address
      email_address&.gsub(/@/, "-deactivated-#{SecureRandom.uuid}@")
    end

    def grant_access_to_everyone_books
      all_accesses = Book.with_everyone_access.ids.collect { |id| { book_id: id, level: :reader } }
      accesses.insert_all(all_accesses)
    end
end

app/models/user/role.rb
module User::Role
  extend ActiveSupport::Concern

  included do
    enum :role, %i[ member administrator ], default: :member
  end

  def can_administer?
    administrator?
  end
end

app/models/user/transferable.rb
module User::Transferable
  extend ActiveSupport::Concern

  TRANSFER_LINK_EXPIRY_DURATION = 4.hours

  class_methods do
    def find_by_transfer_id(id)
      find_signed(id, purpose: :transfer)
    end
  end

  def transfer_id
    signed_id(purpose: :transfer, expires_in: TRANSFER_LINK_EXPIRY_DURATION)
  end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  include UserScoped

  before_action :ensure_current_user, only: %i[ edit update ]

  def show
  end

  def edit
  end

  def update
    @user.update!(user_params)
    redirect_to users_url
  end

  private
    def user_params
      params.require(:user).permit(:name, :email_address, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require_unauthenticated_access only: %i[ new create ]

  before_action :verify_join_code, only: %i[ new create ]
  before_action :ensure_can_administer, only: %i[ update destroy ]
  before_action :set_user, only: %i[ update destroy ]


  def index
    @users = User.active
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create!(user_params)
    start_new_session_for @user
    redirect_to root_url
  rescue ActiveRecord::RecordNotUnique
    redirect_to new_session_url(email_address: user_params[:email_address])
  end

  def update
    @user.update(role_params)
    redirect_to users_url
  end

  def destroy
    @user.deactivate
    redirect_to users_url
  end

  private
    def role_params
      { role: params.require(:user)[:role].presence_in(%w[ member administrator ]) || "member" }
    end

    def set_user
      @user = User.active.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email_address, :password)
    end

    def verify_join_code
      head :not_found if Current.account.join_code != params[:join_code]
    end
end

app/views/users/_invite.html.erb
<div class="flex flex-column align-center gap txt-medium--responsive">
  <% url = join_url(Current.account.join_code) %>

  <label class="flex flex-column gap full-width txt-align-center">
    <strong id="invite_label" class="invite-label">Share to invite more people</strong>
    <span class="flex align-center gap margin-inline">
      <input type="text" class="input fill-white" id="invite_url" value="<%= url %>" aria-labelledby="invite_label" readonly>
    </span>
  </label>

  <div class="flex align-center gap">
    <div data-controller="dialog" class="flex-inline">
      <%= tag.button class: "btn", data: { action: "dialog#open" } do %>
        <%= image_tag "qr-code.svg", aria: { hidden: "true" }, size: 24, class: "colorize--black" %>
        <span class="for-screen-reader">Show join link QR code</span>
      <% end %>

      <dialog class="dialog panel shadow" data-dialog-target="dialog">
        <%= qr_code_image(url) %>

        <form method="dialog" class="flex justify-center">
          <button class="btn panel__close" title="Close (esc)">
            <%= image_tag "remove.svg", aria: { hidden: true }, size: 24 %>
            <span class="for-screen-reader">Close (esc)</span>
          </button>
        </form>
      </dialog>
    </div>

    <%= button_to_copy_to_clipboard(url) do %>
      <%= image_tag "copy-paste.svg", aria: { hidden: "true" }, size: 24, class: "colorize--black" %>
      <span class="for-screen-reader">Copy join link</span>
    <% end %>

    <%= web_share_button(url, "Link to join Writebook", "Hit this link to join me in Writebook and start writing.") do %>
      <%= image_tag "share.svg", aria: { hidden: "true" }, size: 24, class: "colorize--black" %>
      <span class="for-screen-reader">Share join link</span>
    <% end %>

    <% if Current.user.can_administer? %>
      <%= button_to account_join_code_path, class: "btn btn--regenerate" do %>
        <%= image_tag "refresh.svg", aria: { hidden: "true" }, size: 24, class: "colorize--black" %>
        <span class="for-screen-reader">Regenerate join link</span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/_transfer.html.erb
<div class="flex flex-column align-center gap txt-medium--responsive">
  <% url = session_transfer_url(user.transfer_id) %>

  <label class="flex flex-column gap full-width">
    <div class="flex align-center gap">
      <% if Current.user != user %>
        <%= translation_button(:transfer_session) %>
        <strong id="session_transfer_label" class="txt-align-start">Share to get them back into their account</strong>
      <% else %>
        <%= translation_button(:transfer_session_self) %>
        <strong id="session_transfer_label" class="txt-align-start">Link to automatically log in on another device</strong>
      <% end %>
    </div>
    <span class="flex align-center gap margin-inline">
      <input type="text" class="input fill-white" id="session_transfer_url" value="<%= url %>" aria-labelledby="session_transfer_label" readonly>
    </span>
  </label>

  <div class="flex align-center gap">
    <div data-controller="dialog" class="flex-inline">
      <%= tag.button class: "btn", data: { action: "dialog#open" } do %>
        <%= image_tag "qr-code.svg", aria: { hidden: "true" }, size: 24, class: "colorize--black" %>
        <span class="for-screen-reader">Show auto-login QR code</span>
      <% end %>

      <dialog class="dialog panel shadow" data-dialog-target="dialog">
        <%= qr_code_image(url) %>

        <form method="dialog" class="flex justify-center">
          <button class="btn panel__close" title="Close (esc)">
            <%= image_tag "remove.svg", aria: { hidden: true }, size: 24 %>
            <span class="for-screen-reader">Close (esc)</span>
          </button>
        </form>
      </dialog>
    </div>

    <%= button_to_copy_to_clipboard(url) do %>
      <%= image_tag "copy-paste.svg", aria: { hidden: "true" }, size: 24, class: "colorize--black" %>
      <span class="for-screen-reader">Copy auto-login link</span>
    <% end %>

    <%= web_share_button(url, "Your sign-in link", "This is your own private sign-in URL, DO NOT SHARE IT. Use it to sign-in on another device or if you get locked out.") do %>
      <%= image_tag "share.svg", aria: { hidden: "true" }, size: 24, class: "colorize--black" %>
      <span class="for-screen-reader">Share auto-login link</span>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<div class="flex align-center gap-half pad-inline txt-medium--responsive">
  <strong class="overflow-ellipsis txt-medium--responsive"><%= link_to user.name, user.current? ? edit_user_profile_path(user) : user_profile_path(user) %></strong>
  <hr class="flex-item-grow margin-none" aria-hidden="true">

  <%= form_with model: user, url: user_path(user), data: { controller: "form" }, method: :patch do | form | %>
    <label class="btn btn--small flex-item-no-shrink" for="<%= dom_id(user, :role) %>">
      <span class="for-screen-reader"><%= user.name %>'s role: <%= user.administrator? ? "Administrator" : "Member" %></span>
      <%= image_tag "crown.svg", size: 24, aria: { hidden: "true" } %>
      <%= form.check_box :role, { data: { action: "form#submit" }, hidden: true, id: dom_id(user, :role), disabled: ("disabled" if user.current? || !Current.user.can_administer?) }, "administrator", "member" %>
    </label>
  <% end %>

  <%= button_to user_path(user), method: :delete, class: "btn btn--small btn--negative flex-item-no-shrink", disabled: ("disabled" if user.current? || !Current.user.can_administer?), data: {
        turbo_confirm: "Are you sure you want to permanently remove this person from the account? This can’t be undone."} do %>
    <%= image_tag "minus.svg", aria: { hidden: true }, size: 24 %>
    <span class="for-screen-reader">Remove <%= user.name %> from the account</span>
  <% end %>
</div>

app/views/users/index.html.erb
<% content_for(:title) { "People on the account" } %>

<% content_for :header do %>
  <nav>
    <%= link_to root_path, class: "btn" do %>
      <%= image_tag "arrow-left.svg", aria: { hidden: true }, size: 24 %>
      <span class="for-screen-reader">Go back</span>
    <% end %>

    <div class="breadcrumbs">
      <%= render "books/index_link" %>
      <span class="flex-item-no-shrink">▸</span>
      <%= image_tag "settings.svg", aria: { label: "Settings" }, size: 19, class: "colorize--black", alt: "Settings" %>
    </div>

    <% if Current.user.can_administer? %>
      <%= link_to edit_account_custom_styles_url, class: "btn" do %>
        <%= image_tag "art.svg", aria: { hidden: true }, size: 24 %>
        <span class="for-screen-reader">Custom styles</span>
      <% end %>
    <% end %>
  </nav>
<% end %>

<div class="panel borderless center pad fill-shade flex flex-column margin-block">
  <%= render "invite" %>
</div>

<div class="panel borderless center pad fill-none flex flex-column gap">
  <%= render @users %>
</div>

<% content_for(:footer) do %>
  <div class="txt-align-center center margin-block-double txt-subtle">Writebook&trade; version <%= version_badge %></div>
<% end %>

app/views/users/new.html.erb
<% content_for(:title) { "Create your account" } %>
<% turbo_page_requires_reload %>

<% content_for :header do %>
  <nav>
    <%= link_to new_session_path, class: "btn flex-item-justify-end" do %>
      <%= image_tag "login-keys.svg", aria: { hidden: true }, size: 24 %>
      <span class="for-screen-reader">Sign in instead</span>
    <% end %>
  </nav>
<% end %>

<div class="panel shadow center <%= "shake" if flash[:alert] %>">
  <%= image_tag "writebook-icon.svg", class: "product__logo center colorize--black", size: 130 %>
  <h1 class="margin-none-block-start margin-block-end-double">Writebook</h1>

  <%= form_with model: @user, url: join_path(params[:join_code]), class: "flex flex-column gap" do |form| %>
    <div class="flex align-center gap">
      <%= translation_button(:user_name) %>
      <label class="flex align-center gap input input--actor">
        <%= form.text_field :name, class: "input full-width", autocomplete: "name", placeholder: "Name", autofocus: true, required: true, data: { "1p-ignore": true } %>
        <%= image_tag "person.svg", aria: { hidden: "true" }, size: 30, class: "colorize--black" %>
      </label>
    </div>
    <div class="flex align-center gap">
      <%= translation_button(:email_address) %>
      <label class="flex align-center gap input input--actor">
        <%= form.email_field :email_address, class: "input full-width", autocomplete: "username", placeholder: "Email address", required: true %>
        <%= image_tag "email.svg", aria: { hidden: "true" }, size: 30, class: "colorize--black" %>
      </label>
    </div>
    <div class="flex align-center gap">
      <%= translation_button(:password) %>
      <label class="flex align-center gap input input--actor">
        <%= form.password_field :password, class: "input full-width", autocomplete: "new-password", placeholder: "Password", required: true, maxlength: 72 %>
        <%= image_tag "password.svg", aria: { hidden: "true" }, size: 30, class: "colorize--black" %>
      </label>
    </div>
    <button type="submit" id="log_in" class="btn btn--reversed center">
      <%= image_tag "arrow-right.svg", aria: { hidden: true }, size: 24 %>
      <span class="for-screen-reader">Sign in</span>
    </button>
  <% end %>
</div>