config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  resource :first_run, only: %i[ show create ]

  resource :session, only: %i[ new create destroy ] do
    scope module: "sessions" do
      resources :transfers, only: %i[ show update ]
    end
  end

  get "join/:join_code", to: "users#new", as: :join
  post "join/:join_code", to: "users#create"

  resource :account do
    scope module: "accounts" do
      resource :join_code, only: :create
      resource :custom_styles, only: %i[ edit update ]
    end
  end

  resources :books, except: %i[ ] do
    resource :publication, controller: "books/publications", only: %i[ show edit update ]
    resource :bookmark, controller: "books/bookmarks", only: :show

    scope module: "books" do
      namespace :leaves do
        resources :moves, only: :create
      end

      resource :search
    end

    resources :sections
    resources :pictures
    resources :pages
  end

  get "/:id/:slug", to: "books#show", constraints: { id: /\d+/ }, as: :slugged_book
  get "/:book_id/:book_slug/:id/:slug", to: "leafables#show", constraints: { book_id: /\d+/, id: /\d+/ }, as: :slugged_leafable

  direct :book_slug do |book, options|
    route_for :slugged_book, book, book.slug, options
  end

  direct :leafable_slug do |leaf, options|
    route_for :slugged_leafable, leaf.book, leaf.book.slug, leaf, leaf.slug, options
  end

  resources :pages, only: [] do
    scope module: "pages" do
      resources :edits, only: :show
    end
  end

  resources :qr_code, only: :show
  resources :users do
    scope module: "users" do
      resource :profile
    end
  end

  direct :leafable do |leaf, options|
    route_for "book_#{leaf.leafable_name}", leaf.book, leaf, options
  end

  direct :edit_leafable do |leaf, options|
    route_for "edit_book_#{leaf.leafable_name}", leaf.book, leaf, options
  end

  namespace :action_text, path: nil do
    get "/u/*slug" => "markdown/uploads#show", as: :markdown_upload
    post "/uploads" => "markdown/uploads#create", as: :markdown_uploads
  end

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/book.rb
class Book < ApplicationRecord
  include Accessable, Sluggable

  has_many :leaves, dependent: :destroy
  has_one_attached :cover, dependent: :purge_later

  scope :ordered, -> { order(:title) }
  scope :published, -> { where(published: true) }

  enum :theme, %w[ black blue green magenta orange violet white ].index_by(&:itself), suffix: true, default: :blue

  def press(leafable, leaf_params)
    leaves.create! leaf_params.merge(leafable: leafable)
  end
end

app/models/book/accessable.rb
module Book::Accessable
  extend ActiveSupport::Concern

  included do
    has_many :accesses, dependent: :destroy
    scope :with_everyone_access, -> { where(everyone_access: true) }
  end

  class_methods do
    def accessable_or_published(user: Current.user)
      if user.present?
        accessable_or_published_books
      else
        published
      end
    end

    def accessable_or_published_books(user: Current.user)
      user.books.or(published).distinct
    end
  end

  def accessable?(user: Current.user)
    accesses.exists?(user: user)
  end

  def editable?(user: Current.user)
    access_for(user: user)&.editor? || user&.administrator?
  end

  def access_for(user: Current.user)
    accesses.find_by(user: user)
  end

  def update_access(editors:, readers:)
    editors = Set.new(editors)
    readers = Set.new(everyone_access? ? User.active.ids : readers)

    all = editors + readers
    all_accesses = all.collect { |user_id|
      { user_id: user_id, level: editors.include?(user_id) ? :editor : :reader }
    }

    accesses.upsert_all(all_accesses, unique_by: [ :book_id, :user_id ])
    accesses.where.not(user_id: all).delete_all
  end
end

app/models/book/sluggable.rb
module Book::Sluggable
  extend ActiveSupport::Concern

  included do
    before_save :generate_slug, if: -> { slug.blank? }
  end

  def generate_slug
    self.slug = title.parameterize
  end
end

app/controllers/books/bookmarks_controller.rb
class Books::BookmarksController < ApplicationController
  allow_unauthenticated_access

  include BookScoped

  def show
    @leaf = @book.leaves.active.find_by(id: last_read_leaf_id) if last_read_leaf_id.present?
  end

  private
    def last_read_leaf_id
      cookies["reading_progress_#{@book.id}"]
    end
end

app/controllers/books/leaves/moves_controller.rb
class Books::Leaves::MovesController < ApplicationController
  include BookScoped

  before_action :ensure_editable

  def create
    leaf, *followed_by = leaves
    leaf.move_to_position(position, followed_by: followed_by)
  end

  private
    def position
      params[:position].to_i
    end

    def leaves
      @book.leaves.find(Array(params[:id]))
    end
end

app/controllers/books/publications_controller.rb
class Books::PublicationsController < ApplicationController
  include BookScoped

  before_action :ensure_editable, only: %i[ edit update ]

  def show
  end

  def edit
  end

  def update
    @book.update! book_params
    redirect_to book_slug_url(@book)
  end

  private
    def book_params
      params.require(:book).permit(:published, :slug)
    end
end

app/controllers/books/searches_controller.rb
class Books::SearchesController < ApplicationController
  allow_unauthenticated_access

  include BookScoped

  def create
    @leaves = @book.leaves.active.search(params[:search]).favoring_title.limit(50)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  allow_unauthenticated_access only: %i[ index show ]

  before_action :ensure_index_is_not_empty, only: :index
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :set_users, only: %i[ new edit ]
  before_action :ensure_editable, only: %i[ edit update destroy ]

  protect_from_forgery unless: -> { request.format.json? }

  def index
    @books = Book.accessable_or_published.ordered
  end

  def new
    @book = Book.new
  end

  def create
    book = Book.create! book_params
    update_accesses(book)

    redirect_to book_slug_url(book)
  end

  def show
    @leaves = @book.leaves.active.with_leafables.positioned
  end

  def edit
  end

  def update
    @book.update(book_params)
    update_accesses(@book)
    remove_cover if params[:remove_cover] == "true"

    redirect_to book_slug_url(@book)
  end

  def destroy
    @book.destroy

    redirect_to root_url
  end

  private
    def set_book
      @book = Book.accessable_or_published.find params[:id]
    end

    def set_users
      @users = User.active.ordered
    end

    def ensure_editable
      head :forbidden unless @book.editable?
    end

    def ensure_index_is_not_empty
      if !signed_in? && Book.published.none?
        require_authentication
      end
    end

    def book_params
      params.require(:book).permit(:title, :subtitle, :author, :cover, :remove_cover, :everyone_access, :theme)
    end

    def update_accesses(book)
      editors = [ Current.user.id, *params[:editor_ids]&.map(&:to_i) ]
      readers = [ Current.user.id, *params[:reader_ids]&.map(&:to_i) ]

      book.update_access(editors: editors, readers: readers)
    end

    def remove_cover
      @book.cover.purge
    end
end

app/helpers/books/editing_helper.rb
module Books::EditingHelper
  def editing_mode_toggle_switch(leaf, checked:)
    target_url = checked ? leafable_slug_path(leaf) : edit_leafable_path(leaf)
    render "books/edit_mode", target_url: target_url, checked: checked
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def book_toc_tag(book, &)
    tag.ol class: "toc", tabindex: 0,
      data: {
        controller: "arrangement",
        action: arrangement_actions,
        arrangement_cursor_class: "arrangement-cursor",
        arrangement_selected_class: "arrangement-selected",
        arrangement_placeholder_class: "arrangement-placeholder",
        arrangement_move_mode_class: "arrangement-move-mode",
        arrangement_url_value: book_leaves_moves_url(book)
      }, &
  end

  def book_part_create_button(book, kind, **, &)
    url = url_for [ book, kind.new ]

    button_to url, class: "btn btn--plain txt-medium fill-transparent disable-when-arranging disable-when-deleting", draggable: true,
      data: {
        action: "dragstart->arrangement#dragStartCreate dragend->arrangement#dragEndCreate",
        arrangement_url_param: url
      }, **, &
  end

  def link_to_first_leafable(leaves)
    if first_leaf = leaves.first
      link_to leafable_slug_path(first_leaf), data: hotkey_data_attributes("right"), class: "disable-when-arranging", hidden: true do
        tag.span(class: "btn") do
          image_tag("arrow-right.svg", aria: { hidden: true }, size: 24) + tag.span("Start reading", class: "for-screen-reader")
        end + tag.span(first_leaf.title, class: "overflow-ellipsis")
      end
    end
  end

  def link_to_previous_leafable(leaf, hotkey: true, for_edit: false)
    if previous_leaf = leaf.previous
      path = for_edit ? edit_leafable_path(previous_leaf) : leafable_slug_path(previous_leaf)
      link_to path, data: hotkey_data_attributes("left", enabled: hotkey), class: "btn" do
        image_tag("arrow-left.svg", aria: { hidden: true }, size: 24) + tag.span("Previous: #{ previous_leaf.title }", class: "for-screen-reader")
      end
    else
      link_to book_slug_path(leaf.book), data: hotkey_data_attributes("left", enabled: hotkey), class: "btn" do
        image_tag("arrow-left.svg", aria: { hidden: true }, size: 24) + tag.span("Table of contents: #{ leaf.book.title }", class: "for-screen-reader")
      end
    end
  end

  def link_to_next_leafable(leaf, hotkey: true, for_edit: false)
    if next_leaf = leaf.next
      path = for_edit ? edit_leafable_path(next_leaf) : leafable_slug_path(next_leaf)
      link_to path, data: hotkey_data_attributes("right", enabled: hotkey), class: "btn txt-medium min-width" do
        tag.span("Next: #{next_leaf.title }", class: "overflow-ellipsis") + image_tag("arrow-right.svg", aria: { hidden: true }, size: 24)
      end
    else
      link_to book_slug_path(leaf.book), data: hotkey_data_attributes("right", enabled: hotkey), class: "btn txt-medium" do
        tag.span("Table of contents: #{leaf.book.title }", class: "overflow-ellipsis") + image_tag("arrow-reverse.svg", aria: { hidden: true }, size: 24)
      end
    end
  end

  private
    def hotkey_data_attributes(key, enabled: true)
      if enabled
        { controller: "hotkey", action: "keydown.#{key}@document->hotkey#click touch:swipe-#{key}@window->hotkey#click" }
      end
    end
end

app/views/books/publications/_publication.html.erb
<div class="flex flex-column gap margin-block-start pad <%= book.published? ? "fill-selected" : "fill-shade" %> border-radius">
  <% if book.editable? %>
    <div class="flex align-center justify-center gap-half center">
      <%= image_tag "lock.svg", aria: { hidden: true }, size: 36, class: "colorize--black" %>
        <%= form_with model: book, url: book_publication_path(book), data: { controller: "form", action: "change->form#submit" }, html: { contents: true } do |form| %>
          <label class="switch txt-medium">
            <%= form.check_box :published, checked: book.published?, class: "switch__input" %>
            <span class="switch__btn round"></span>
            <span class="for-screen-reader">Publish this book</span>
          </label>
        <% end %>
      <%= image_tag "world.svg", aria: { hidden: true }, size: 36, class: "colorize--black" %>
    </div>
  <% end %>

  <% if book.published? %>
    <div class="flex flex-column align-center gap txt-medium">
      <% public_url = book_slug_url(book) %>

      <label class="flex flex-column gap full-width txt-align-center">
        <strong id="invite_label" class="invite-label for-screen-reader">Public link to this book</strong>
        <input type="text" class="input fill-white" id="invite_url" value="<%= public_url %>" aria-labelledby="invite_label" readonly>
      </label>

      <div class="flex align-center gap">
        <div data-controller="dialog" class="flex-inline">
          <%= tag.button class: "btn", data: { action: "dialog#open" } do %>
            <%= image_tag "qr-code.svg", aria: { hidden: "true" }, size: 24, class: "colorize--black" %>
            <span class="for-screen-reader">Show public link QR code</span>
          <% end %>

          <dialog class="dialog panel shadow" data-dialog-target="dialog">
            <%= qr_code_image(public_url) %>

            <form method="dialog" class="flex justify-center">
              <button class="btn panel__close" title="Close (esc)">
                <%= image_tag "remove.svg", aria: { hidden: true }, size: 24 %>
                <span class="for-screen-reader">Close</span>
              </button>
            </form>
          </dialog>
        </div>

        <%= button_to_copy_to_clipboard(public_url) do %>
          <%= image_tag "copy-paste.svg", aria: { hidden: "true" }, size: 24, class: "colorize--black" %>
          <span class="for-screen-reader">Copy public link</span>
        <% end %>

        <%= web_share_button(public_url, "Link to join Writebook", "Hit this link to join me in Writebook and start writing.") do %>
          <%= image_tag "share.svg", aria: { hidden: "true" }, size: 24, class: "colorize--black" %>
          <span class="for-screen-reader">Share public link</span>
        <% end %>

        <% if book.editable? %>
          <%= link_to edit_book_publication_path(book), class: "btn" do %>
            <%= image_tag "pencil.svg", aria: { hidden: "true" }, size: 24, class: "colorize--black" %>
            <span class="for-screen-reader">Edit link URL</span>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/books/publications/edit.html.erb
<%= turbo_frame_tag @book, :publication do %>
  <div class="flex flex-column gap margin-block-start pad fill-shade border-radius <%= "shake" if @book.errors[:slug].any? %>">
    <div class="flex flex-column align-center gap txt-medium">
      <% public_url = book_url(@book) %>

      <%= form_with model: @book, url: book_publication_path(@book), class: "max-width", data: { turbo_frame: "_top" } do |form| %>
        <%= form.hidden_field :publication, value: true %>

        <label class="flex flex-column gap full-width txt-align-center">
          <div id="public_link_label" class="flex align-center gap justify-center">
            <strong>Edit publication link</strong>
          </div>
          <span class="input input--actor flex align-center fill-white">
            <%= "#{request.host}/#{@book.id}/" %>
            <%= form.text_field :slug,
                  autofocus: true,
                  class: class_names("input"),
                  required: true,
                  pattern: "^[\\-A-Za-z0-9]+$",
                  title: "Enter letters, numbers, or hyphens only" %>
          </span>
        </label>

        <div class="flex align-center gap margin-inline margin-block-start">
          <button type="submit" class="btn btn--positive flex-item-justify-end">
            <%= image_tag "check.svg", aria: { hidden: true }, size: 24 %>
            <span class="for-screen-reader">Save</span>
          </button>

          <%= link_to book_slug_path(@book), class: "btn flex-item-justify-start" do %>
            <%= image_tag "remove.svg", aria: { hidden: true }, size: 24 %>
            <span class="for-screen-reader">Cancel</span>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/books/publications/show.html.erb
<%= turbo_frame_tag @book, :publication do %>
  <%= render "publication", book: @book %>
<% end %>