config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  resource :first_run, only: %i[ show create ]

  resource :session, only: %i[ new create destroy ] do
    scope module: "sessions" do
      resources :transfers, only: %i[ show update ]
    end
  end

  get "join/:join_code", to: "users#new", as: :join
  post "join/:join_code", to: "users#create"

  resource :account do
    scope module: "accounts" do
      resource :join_code, only: :create
      resource :custom_styles, only: %i[ edit update ]
    end
  end

  resources :books, except: %i[ ] do
    resource :publication, controller: "books/publications", only: %i[ show edit update ]
    resource :bookmark, controller: "books/bookmarks", only: :show

    scope module: "books" do
      namespace :leaves do
        resources :moves, only: :create
      end

      resource :search
    end

    resources :sections
    resources :pictures
    resources :pages
  end

  get "/:id/:slug", to: "books#show", constraints: { id: /\d+/ }, as: :slugged_book
  get "/:book_id/:book_slug/:id/:slug", to: "leafables#show", constraints: { book_id: /\d+/, id: /\d+/ }, as: :slugged_leafable

  direct :book_slug do |book, options|
    route_for :slugged_book, book, book.slug, options
  end

  direct :leafable_slug do |leaf, options|
    route_for :slugged_leafable, leaf.book, leaf.book.slug, leaf, leaf.slug, options
  end

  resources :pages, only: [] do
    scope module: "pages" do
      resources :edits, only: :show
    end
  end

  resources :qr_code, only: :show
  resources :users do
    scope module: "users" do
      resource :profile
    end
  end

  direct :leafable do |leaf, options|
    route_for "book_#{leaf.leafable_name}", leaf.book, leaf, options
  end

  direct :edit_leafable do |leaf, options|
    route_for "edit_book_#{leaf.leafable_name}", leaf.book, leaf, options
  end

  namespace :action_text, path: nil do
    get "/u/*slug" => "markdown/uploads#show", as: :markdown_upload
    post "/uploads" => "markdown/uploads#create", as: :markdown_uploads
  end

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/controllers/books/leaves/moves_controller.rb
class Books::Leaves::MovesController < ApplicationController
  include BookScoped

  before_action :ensure_editable

  def create
    leaf, *followed_by = leaves
    leaf.move_to_position(position, followed_by: followed_by)
  end

  private
    def position
      params[:position].to_i
    end

    def leaves
      @book.leaves.find(Array(params[:id]))
    end
end

app/helpers/leaves_helper.rb
module LeavesHelper
  def leaf_item_tag(leaf, **, &)
    tag.li class: "arrangement__item toc__leaf toc__leaf--#{leaf.leafable_name}",
      id: dom_id(leaf),
      data: {
        id: leaf.id,
        arrangement_target: "item"
      }, **, &
  end

  def leaf_nav_tag(leaf, **, &)
    tag.nav data: {
      controller: "reading-tracker",
      reading_tracker_book_id_value: leaf.book_id,
      reading_tracker_leaf_id_value: leaf.id
    }, **, &
  end

  def leafable_edit_form(leafable, **, &)
    form_with model: leafable, url: leafable_path(leafable.leaf), method: :put, format: :html,
    data: {
      controller: "autosave",
      action: "autosave#submit:prevent input@document->autosave#change house-md:change->autosave#change",
      autosave_clean_class: "clean",
      autosave_dirty_class: "dirty",
      autosave_saving_class: "saving"
    }, **, &
  end
end

app/views/leaves/_being_edited_by.turbo_stream.erb
<%= turbo_stream.append dom_id(leaf, :being_edited) do %>
  <%= tag.div id: dom_id(user, :being_edited_by),
        class: "flex-inline align-center justify-center margin-block-end-double txt-medium gap being-edited-by",
        data: { controller: "autoremove", action: "animationend->autoremove#remove", hide_from_user_id: user.id } do %>
    <strong class="margin-inline-end-half"><%= user.name %></strong>
    <span class="spinner txt-small flex-inline"></span>
    <%= image_tag "write.svg", aria: { hidden: true }, size: 18, class: "colorize--white margin-inline-start" %>
  <% end %>
<% end %>

app/views/leaves/_being_edited_indicator.html.erb
<%= turbo_stream_from leaf, :being_edited %>
<%= tag.div id: dom_id(leaf, :being_edited), class: "being-edited-indicator" %>

app/views/leaves/_delete.html.erb
<%= button_to leafable_path(leaf), method: :delete, data: { turbo_confirm: "Are you sure you want to delete this page?" }, class: "btn btn--negative txt-small min-width", form_class: "leaf__delete" do %>
  <%= image_tag "minus.svg", aria: { hidden: true }, size: 24 %>
  <span class="for-screen-reader">Delete <%= leaf.title %></span>
<% end %>

app/views/leaves/_edit.html.erb
<%= leaf_item_tag(leaf) do %>
  <span class="btn btn--link arrangement__handle txt-small">
    <%= image_tag "handle.svg", aria: { hidden: true }, size: 24 %>
    <span class="for-screen-reader">Move <%= leaf.title %></span>
  </span>

  <%= link_to leafable_path(leaf), class: "toc__thumbnail", data: { turbo_frame: "_top" } do %>
    <%= leaf.section.body if leaf.section? %>
    <%= leaf.leafable.body.to_html if leaf.page? %>
    <%= image_tag leaf.leafable.image.variant(:large) if leaf.picture&.image&.attached? %>
  <% end %>

  <div class="toc__title flex align-center min-width">
    <%= form_with model: [ leaf.book, leaf ], url: leafable_path(leaf), class: "flex align-center max-width min-width", id: dom_id(leaf, "form") do |form| %>
      <%= form.text_field :title, class: "input full-width", autofocus: true, autocomplete: "off", data: { controller: "autoselect" } %>
    <% end %>

    <span class="flex align-center gap-half">
      <button type="submit" class="btn txt-small btn--positive" form="<%= dom_id(leaf, "form") %>">
        <%= image_tag "check.svg", aria: { hidden: true }, size: 24 %>
        <span class="for-screen-reader">Save</span>
      </button>

      <%= button_to leafable_path(leaf), method: :delete, class: "btn btn--negative txt-small" do %>
        <%= image_tag "trash.svg", aria: { hidden: true }, size: 24 %>
        <span class="for-screen-reader">Delete this page</span>
      <% end %>
    </span>
  </div>

  <small class="toc__wordcount">
    <% if leaf.page? %>
      <%= word_count(leaf.leafable.body.content) %>
    <% end %>
  </small>

  <%= yield if block_given? %>
<% end %>

app/views/leaves/_edit_footer.html.erb
<% content_for :footer do %>
  <nav class="book__nav flex align-center gap">
    <span class="btn btn--placeholder flex-item-justify-start"></span>

    <%= link_to_next_leafable(leaf, hotkey: false, for_edit: true) %>

    <span class="flex-item-justify-end">
      <%= form_with url: leafable_path(leaf, format: :html), class: "flex align-center gap-half", method: :delete do |form| %>
        <%= form.button class: "btn btn--negative txt-small min-width", data: { turbo_confirm: "Are you sure you want to delete this page?" } do %>
          <%= image_tag "minus.svg", aria: { hidden: true }, size: 24 %>
          <span class="for-screen-reader">Delete <%= @leaf.title %></span>
        <% end %>
      <% end %>
    </span>
  </nav>
<% end %>

app/views/leaves/_header.html.erb
<% content_for :header do %>
  <%= leaf_nav_tag(leaf) do %>
    <%= render "leaves/sidebar_toggle" %>

    <%= link_to_previous_leafable(leaf) %>

    <div class="breadcrumbs">
      <%= render "books/index_link" %>
      <span class="flex-item-no-shrink">▸</span>
      <%= link_to book.title, book_slug_path(book) %>
      <span class="flex-item-no-shrink">▸</span>
      <strong><%= leaf.leafable.title %></strong>
    </div>

    <button class="btn" data-action="fullscreen#toggle" data-fullscreen-target="button">
      <%= image_tag "expand.svg", aria: { hidden: true }, size: 24 %>
      <span class="for-screen-reader">Enter fullscreen</span>
    </button>

    <%= render "books/searches/search", book: @book %>
  <% end %>
<% end %>

<% content_for :toolbar do %>
  <div class="flex flex-column">
    <% if book.editable? %>
      <div class="page-toolbar fill-shade">
        <%= editing_mode_toggle_switch(@leaf, checked: false) %>
      </div>
    <% end %>

    <%= render "books/searches/banner" %>
  </div>
<% end %>

app/views/leaves/_history.html.erb
<% if leaf.edits.any? %>
  <%= link_to page_edit_path(leaf, "latest"), class: "btn flex-item-no-shrink txt-small" do %>
    <%= image_tag "history.svg", aria: { hidden: "true" }, size: "24" %>
    <span class="for-screen-reader">Editing history</span>
  <% end %>
<% end %>

app/views/leaves/_leaf.html.erb
<% cache [ leaf, leaf.book, leaf.book.editable? ] do %>
  <%= leaf_item_tag(leaf) do %>
    <span class="btn btn--link arrangement__handle txt-small">
      <%= image_tag "handle.svg", aria: { hidden: true }, size: 24 %>
      <span class="for-screen-reader">Move <%= leaf.title %></span>
    </span>

    <%= render "leaves/delete", leaf: leaf %>

    <div class="toc__thumbnail <%= "toc__thumbnail--dark" if leaf.section&.theme == "dark" %>">
      <% if leaf.book.editable? %>
        <%= link_to edit_leafable_path(leaf), class: "toc__link hide_from_reading_mode", data: { turbo_frame: "_top" } do %>
          <span class="for-screen-reader">Edit <%= leaf.title %></span>
        <% end %>

        <%= link_to leafable_slug_path(leaf), class: "toc__link hide_from_edit_mode", data: { turbo_frame: "_top" } do %>
          <span class="for-screen-reader">Open <%= leaf.title %></span>
        <% end %>
      <% else %>
        <%= link_to leafable_slug_path(leaf), class: "toc__link", data: { turbo_frame: "_top" } do %>
          <span class="for-screen-reader">Open <%= leaf.title %></span>
        <% end %>
      <% end %>

      <%= tag.span(simple_format(leaf.section.body), class: "txt-align-center") if leaf.section? %>

      <%= sanitize_content leaf.page.html_preview if leaf.page? %>

      <% if leaf.picture? %>
        <%= image_tag leaf.leafable.image.attached? ? leaf.leafable.image.variant(:large) : "default-picture.webp" %>
      <% end %>
    </div>

    <% if leaf.book.editable? %>
      <%= link_to edit_leafable_path(leaf), class: "toc__title min-width hide_from_reading_mode", data: { turbo_frame: "_top" } do %>
        <span class="overflow-ellipsis"><%= leaf.title %></span>
      <% end %>

      <%= link_to leafable_slug_path(leaf), class: "toc__title min-width hide_from_edit_mode", data: { turbo_frame: "_top" } do %>
        <span class="overflow-ellipsis"><%= leaf.title %></span>
      <% end %>
    <% else %>
      <%= link_to leafable_slug_path(leaf), class: "toc__title min-width", data: { turbo_frame: "_top" } do %>
        <span class="overflow-ellipsis"><%= leaf.title %></span>
      <% end %>
    <% end %>

    <span class="toc__bookmark">
      <svg viewBox="0 0 64 64" width="64px" height="64px" xmlns="http://www.w3.org/2000/svg">
        <path d="m17.01 54.01v-42.98.00000045c-.00000025-1.65685 1.34315-3 3-3h24-.00000013c1.65685-.00000007 3 1.34315 3 3v42.98.0001206c0 1.10457-.895431 2-2 2-.34994 0-.693756-.0918173-.997105-.266281l-11.5039-6.61564c-.308638-.17748-.688362-.17748-.997 0l-11.5046 6.6153.00000011-.00000006c-.957413.550849-2.1801.221264-2.73095-.736149-.174564-.303405-.266442-.647312-.266451-.997351z" fill-rule="evenodd" fill="var(--color-marker)" />
      </svg>
    </span>

    <small class="toc__wordcount txt-small--responsive">
      <% if leaf.page? %>
        <%= word_count(leaf.leafable.body.content) %>
      <% end %>
    </small>
  <% end %>
<% end %>

app/views/leaves/_navigation.html.erb
<nav class="book__nav flex align-center gap justify-center">
  <%= link_to_next_leafable(leaf) %>
</nav>

app/views/leaves/_sidebar.html.erb
<menu class="sidebar__content toc flex flex-column">
  <header>
    <h1 class="txt-large--responsive margin-none">
      <%= book.title %>
    </h1>
  </header>

  <% book.leaves.active.with_leafables.positioned.each do |leaf| %>
    <li class="flex min-width <%= "leaf--section" if leaf.section? -%>">
      <% if leaf.book.editable? %>
        <%= link_to edit_leafable_path(leaf), class: "toc__title hide_from_reading_mode min-width", data: { turbo_frame: "_top" } do %>
          <span class="overflow-ellipsis"><%= leaf.title %></span>
        <% end %>

        <%= link_to leafable_slug_path(leaf), class: "toc__title hide_from_edit_mode min-width", data: { turbo_frame: "_top" } do %>
          <span class="overflow-ellipsis"><%= leaf.title %></span>
        <% end %>
      <% else %>
        <%= link_to leafable_slug_path(leaf), class: "toc__title min-width", data: { turbo_frame: "_top" } do %>
          <span class="overflow-ellipsis"><%= leaf.title %></span>
        <% end %>
      <% end %>
    </li>
  <% end %>
</menu>

app/views/leaves/_sidebar_toggle.html.erb
<label class="btn sidebar__toggle" data-controller="sidebar">
  <input type="checkbox" id="sidebar-toggle" data-sidebar-target="toggle" data-action="sidebar#toggle">
  <%= image_tag "sidebar.svg", aria: { hidden: true }, size: 24 %>
  <span class="for-screen-reader">Toggle sidebar</span>
</label>